# Generated by Django 5.2 on 2025-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
    ]
