# Generated by Django 5.2 on 2025-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohope', '0002_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_new', models.BooleanField(default=False)),
                ('key_feature_1', models.CharField(blank=True, max_length=255, null=True)),
                ('key_feature_2', models.CharField(blank=True, max_length=255, null=True)),
                ('key_feature_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
