# Generated by Django 5.2 on 2025-05-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohope', '0004_application_job_delete_jobposting_application_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='crop_images/')),
                ('description', models.TextField()),
                ('guide', models.FileField(blank=True, null=True, upload_to='guides/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_on',
            new_name='submitted_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
