# Generated by Django 5.2 on 2025-05-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohope', '0005_cropsolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='crops/')),
                ('solution_title', models.CharField(max_length=255)),
                ('solution_description', models.TextField()),
                ('guide_pdf', models.FileField(blank=True, null=True, upload_to='guides/')),
                ('product_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
