# Generated by Django 5.2 on 2025-05-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohope', '0006_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
    ]
